# Generated by Django 4.2.6 on 2023-11-09 18:15

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_question_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkedDownExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown_content', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='markdown_description',
            field=markdownx.models.MarkdownxField(default='matrix'),
        ),
    ]
