# Generated by Django 4.2.6 on 2023-11-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_markeddownexample_question_markdown_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='markdown_description',
        ),
    ]
