# Generated by Django 4.2.6 on 2023-11-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_question_markdown_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='markeddownexample',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
