# Generated by Django 4.2.6 on 2023-11-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_markeddownexample_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarkedDownExample',
        ),
    ]
